### ISSUE TITLE
Hello! May I ask you the names of your papers in the README.md?

### ISSUE THREAD

**Issue by blues-green** [gionanide/Speech_Signal_Processing_and_Classification#4]
I noted that some references are quoted in your README.md file, so I guess the README.md may be a part of a paper. May I ask for the name of this paper? I am interested in it and want to learn.  

If it is not convenient, I also want to know some references' names in the README.md: 
(1). Reference 4, where you said: "The aforementioned sort of speaking traditional features will be tested against agnostic-features extracted by convolutive neural networks (CNNs) (e.g., auto-encoders) [4]. ", which is the 10th sentence in the README.md.
(2). Reference 6-8, where you said: "Comparisons will be made against [6-8].", which is the last sentence in the README.md.

 I would greatly appreciate it if you can tell me the names of these papers. Thank you very much!

**Comment by gionanide** [comment]
I am attaching all the books/papers from the README.md 

This file is not from a paper, is a part of a text of my Thesis, unfortunately my thesis is in Greek.

[1]X. Huang, A. Acero, and H.-W. Hon, Spoken Language Processing. Up-
per Saddle River, N.J.: Pearson Education-Prentice Hall, 2001.

[2] J. R. Deller, J. H. L. Hansen, and J. G. Proakis, Discrete-Time Pro-
cessing of Speech Signals. New York, N.Y.: Wiley-IEEE, 1999.

[3] L. R. Rabiner and R. W. Schafer, Theory and Applications of Digital
Speech Processing. Upper Saddle River, N.J.: Pearson Education- Prentice
Hall, 2011.

[4] Wei-Ning Hsu, Yu Zhang, and James R. Glass, Unsupervised Domain
Adaptation for Robust Speech Recognition via Variational Autoencoder-
Based Data Augmentation,2017, http://arxiv.org/abs/1707.06265.

[5] Voice and Speech Laboratory, Massachusetts Eye and Ear Infirmary,
Boston MA,Voice Disorders Database, 1.03 edition, 1994, Kay Elemetrics
Corp.

[6] C. Kotropoulos and G.R. Arce, ”Linear discriminant classifier with re-
ject option for the detection of vocal fold paralysis and vocal fold edema”,
EURASIP Advances in Signal Processing, vol. 2009, article ID 203790, 13
pages, 2009 (DOI:10.1155/2009/203790).

[7] E.Ziogas and C.Kotropoulos, ”Detection of vocal fold paralysis and
edema using linear discriminant classifiers” in Proc. 4th Panhellenic Ar-
tificial Intelligence Conf. (SETN-06), Heraklion, Greece, vol. LNAI 3966,
pp. 454-464, May 19-20, 2006.

[8] M.Marinaki, C.Kotropoulos, I.Pitas, and N.Maglaveras, ”Automatic de-
tection of vocal fold paralysis and edema” in Proc. 8th Int. Conf. Spoken
Language Processing (INTERSPEECH 2004), Jeju, Korea, pp. 537-540, Oc-
tober, 2004.
